console.log("Primeira linha \n Segunda linha")
console.log("'String entre aspas simples'")
console.log('"String entre aspas duplas"')
console.log(`A soma de 2+4 é igual a ${2+4}`)
console.log("Concatenando"+" Strings")